# Generated by Django 3.2.25 on 2026-02-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnotification',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='left',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='right',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='top',
        ),
    ]
